project/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, IntegerField, TextAreaField, BooleanField, SelectField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo, InputRequired, Optional


class LoginForm(FlaskForm):
    username = StringField("User Name", [DataRequired()])
    password = PasswordField("Password", [DataRequired()])


class RegisterForm(FlaskForm):
    username = StringField(
        "User Name",
        validators=[
            DataRequired()
        ]
    )
    
    email = StringField(
        "Email Address",
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40),
        ],
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Confirm password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )


class RemoveUser(FlaskForm):
    username = StringField("User Name", [DataRequired()])


class RemoveRecord(FlaskForm):
    strat_no = IntegerField("SA Strat No", [DataRequired()])


class StratForm(FlaskForm):
    unit_name = StringField("Unit Name", [InputRequired()])
    ASUD_No = IntegerField("ASUD No", [Optional()])
    ASUD_definition_card = BooleanField("ASUD definition card exists")
    strat_no = IntegerField("SA Strat Unit No", [InputRequired()])
    map_symbol = StringField("Map Symbol", [Length(max=8)])
    province = StringField('Province', [Length(max=60)])
    domain = StringField('Domain/Sub-province', [Length(max=60)])
    unit_description = TextAreaField("Stratigraphic Unit Description", [Length(max=500)])
    unit_summary = TextAreaField("Stratigraphic Unit Summary", [Length(max=2000)])
    type_locality = TextAreaField("Type Locality", [Length(max=300)])
    unit_definition = TextAreaField("Unit Definition", [Length(max=6000)])
    unit_correlation = TextAreaField("Unit Correlations", [Length(max=2000)])
    unit_distribution = TextAreaField("Unit Distribution", [Length(max=2000)])
    unit_thickness = TextAreaField("Unit Thickness", [Length(max=2000)])
    unit_lithology = TextAreaField("Unit Lithology", [Length(max=8000)])
    unit_deposition_env = TextAreaField("Unit Depositional Environment", [Length(max=4000)])
    unit_contact_relations = TextAreaField("Unit Contact Relationships", [Length(max=4000)])
    unit_geochronology = TextAreaField("Unit Geochronology", [Length(max=4000)])
    unit_geochemistry = TextAreaField("Unit Geochemistry", [Length(max=4000)])
    unit_geophysical_expression = TextAreaField("Unit Geophysical Expression", [Length(max=4000)])
    references = TextAreaField("References", [Length(max=6000)])


class SearchForm(FlaskForm):
    select = SelectField("Search for a Stratigraphic Unit", choices=[
                ('unit_name','Unit Name'), ('strat_no','SA Strat No'),
                ('map_symbol','Map Symbol')
            ])
    search = StringField('')


class ResetPasswordRequestForm(FlaskForm):
    email = StringField('Email', [DataRequired(), Email()])
    


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', [DataRequired()])
    password2 = PasswordField('Repeat Password', [DataRequired(), EqualTo('password')])
    

project/server/user/__init__.py
# project/server/user/__init__.py

project/server/user/views.py
# project/server/user/views.py


from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, current_user

from project.server import bcrypt, db
from project.server.models import User, Stratigraphy
from project.server.utils import row2dict, send_password_reset_email
from project.server.user.forms import LoginForm, RegisterForm, RemoveUser, StratForm, ResetPasswordRequestForm, ResetPasswordForm, RemoveRecord
from project.server.user.tables import IndexTable


user_blueprint = Blueprint("user", __name__)


@user_blueprint.route("/admin", methods=["GET"])
@login_required
def admin():
    user_list = db.session.query(User.id, User.username, User.email).order_by(User.id)
    #register_form = RegisterForm(request.form)
    #remove_form = RemoveUser(request.form)
    return render_template("user/admin.html", user_list = user_list, register_form=RegisterForm(), remove_form=RemoveUser(), remove_record=RemoveRecord())

@user_blueprint.route("/admin/register", methods=["POST"])
@login_required
def register():
    user_list = db.session.query(User.id, User.username, User.email).order_by(User.id)
    register_form = RegisterForm(request.form)
    #remove_form = RemoveUser(request.form)
    if register_form.validate_on_submit():
        User.create(
           username=register_form.username.data,
           email=register_form.email.data,
           password=register_form.password.data
        )
        flash("Successfully registered new user.", "success")
        return redirect(url_for("user.admin"))
    return render_template("user/admin.html", user_list = user_list, register_form=register_form, remove_form=RemoveUser(), remove_record=RemoveRecord())

@user_blueprint.route("/admin/remove", methods=["POST"])
@login_required
def remove():        
    user_list = db.session.query(User.id, User.username, User.email).order_by(User.id)
    #register_form = RegisterForm(request.form)
    remove_form = RemoveUser(request.form)
    if remove_form.validate_on_submit():
        user = User.query.filter_by(username=remove_form.username.data).first()
        if user:
            user.delete()
            flash(f"successfully removed {user}.", "success")
            return redirect(url_for("user.admin"))
        else:
            flash(f"{remove_form.username.data} not in database", "warning" )
            return redirect(url_for("user.admin"))

    return render_template("user/admin.html", user_list = user_list, register_form=RegisterForm(), remove_form=remove_form, remove_record=RemoveRecord())

@user_blueprint.route("/admin/delete", methods=["POST"])
@login_required
def delete_record():
    user_list = db.session.query(User.id, User.username, User.email).order_by(User.id)
    #register_form = RegisterForm(request.form)
    remove_record = RemoveRecord(request.form)
    if remove_record.validate_on_submit():
        strat_no = Stratigraphy.query.filter_by(strat_no=remove_record.strat_no.data).first()
        if strat_no:
            strat_no.delete()
            flash(f"successfully removed unit {strat_no}.", "success")
            return redirect(url_for("user.admin"))
        else:
            flash(f"No entry with unit no {remove_record.strat_no.data}", "warning")
            return redirect(url_for("user.admin"))
    
    return render_template("user/admin.html", user_list = user_list, register_form=RegisterForm(), remove_form=RemoveUser(), remove_record=remove_record)

@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(
            user.password, request.form["password"]
        ):
            login_user(user)
            flash("You are logged in. Welcome!", "success")
            return redirect(url_for("user.index"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("user/login.html", form=form)
    return render_template("user/login.html", title="Please Login", form=form)


@user_blueprint.route("/reset_password_request", methods=["GET", "POST"])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    form = ResetPasswordRequestForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash("Check your email for instructions to reset your password", "success")
        return(redirect(url_for('user.login')))
    return render_template('user/reset_password_request.html', form=form)


@user_blueprint.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('main.home'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.', 'success')
        return redirect(url_for('user.login'))
    return render_template('user/reset_password.html', form=form)

@user_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out. Bye!", "success")
    return redirect(url_for("main.home"))


@user_blueprint.route("/data_entry", methods=["GET", "POST"])
@login_required
def data_entry():
    
    return render_template("user/data_entry.html", entry_form=StratForm())

@user_blueprint.route("/data_entry/new", methods=["GET", "POST"])
@login_required
def new_entry():
    "Enter Strat data into the db"

    entry_form = StratForm(request.form)
    if request.method == "POST" and entry_form.validate_on_submit():
        strat_no = Stratigraphy.query.filter_by(strat_no=entry_form.strat_no.data).first()
        if not strat_no:
            Stratigraphy.create(
                unit_name= entry_form.unit_name.data,
                ASUD_No=entry_form.ASUD_No.data,
                ASUD_definition_card=entry_form.ASUD_definition_card.data,
                strat_no=entry_form.strat_no.data,
                map_symbol=entry_form.map_symbol.data,
                province=entry_form.province.data,
                domain=entry_form.domain.data,
                unit_description=entry_form.unit_description.data,
                unit_summary=entry_form.unit_summary.data,
                type_locality=entry_form.type_locality.data,
                unit_definition=entry_form.unit_definition.data,
                unit_correlation=entry_form.unit_correlation.data,
                unit_distribution=entry_form.unit_distribution.data,
                unit_thickness=entry_form.unit_thickness.data,
                unit_lithology=entry_form.unit_lithology.data,
                unit_deposition_env=entry_form.unit_deposition_env.data,
                unit_contact_relations=entry_form.unit_contact_relations.data,
                unit_geochronology=entry_form.unit_geochronology.data,
                unit_geochemistry=entry_form.unit_geochemistry.data,
                unit_geophysical_expression=entry_form.unit_geophysical_expression.data,
                references=entry_form.references.data,
                compiler_id=current_user.get_id()
            )
            flash("You have successfully entered a new unit description", "success")
            return redirect(url_for("user.index"))
        else:
            flash("That SA Strat No already exists","warning")
            return redirect(url_for("user.data_entry"))
                
    return render_template("user/data_entry.html", entry_form=entry_form)


@user_blueprint.route("/view/<int:id>", methods=["GET", "POST"])
@login_required
def view(id):
    record = Stratigraphy.query.filter_by(id=id).first()
    record_dict = row2dict(record)
    if record:

        return render_template("user/view_record.html", record=record_dict)

    return render_template("user/index.html")


@user_blueprint.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
def edit(id):
    record = Stratigraphy.query.filter_by(id=id).first()
    form = StratForm(request.form, obj=record)
    if record:
        if request.method == "POST" and form.validate_on_submit():
            form.populate_obj(record)
            Stratigraphy.update(record, edited_id=current_user.get_id())
            flash("Record updated", "success")
            return redirect(url_for('user.index'))
        return render_template('user/edit_record.html', entry_form=form)
    else:
        flash("Error loading record #{id}".format(id=id), "warning")
        
    return render_template("user/index.html")


@user_blueprint.route("/index")
@login_required
def index():
    entry_count = db.session.query(Stratigraphy.id).count()
    entry_list = db.session.query(
                Stratigraphy.id, Stratigraphy.unit_name, Stratigraphy.strat_no,
                Stratigraphy.map_symbol).order_by(Stratigraphy.map_symbol)
    table = IndexTable(entry_list)

    return render_template("user/index.html", entry_count=entry_count, table=table)

project/client/templates/user/admin.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Administer users</h1>
    <hr><br>
  </header>

  <br>

  <div class="table-striped">
    <table class="table">
      <tr>
        <th>Id</th>
        <th>User name</th>
        <th>Email</th>
      </tr>
      {% for row in user_list %}
      <tr>
        <td>{{ row.id }}</td>
        <td>{{ row.username }}</td>
        <td>{{ row.email }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>

  <div class="title">
    <h3>Add user</h3>
  </div>

  <form class="form" role="form" method="post" action="{{ url_for('user.register') }}">
    {{ register_form.csrf_token }}
    {{ register_form.hidden_tag() }}
    {{ wtf.form_errors(register_form, hiddens="only") }}

    <div class="form-row">
      {{ wtf.form_field(register_form.username )}}
      {{ wtf.form_field(register_form.email) }}
      {{ wtf.form_field(register_form.password) }}
      {{ wtf.form_field(register_form.confirm) }}
    </div>
    <div class="form">
      <button class="btn btn-success" type="submit">Add new user</button>
      <br><br>
    </div>
  </form>

  <div class="title">
    <h3>Remove user</h3>
  </div>

  <form class="form" role="form" method="post" action="{{ url_for('user.remove') }}">
    {{ remove_form.csrf_token }}
    {{ remove_form.hidden_tag() }}
    {{ wtf.form_errors(remove_form, hiddens="only") }}

    <div class="form-row">
      {{ wtf.form_field(remove_form.username )}}
      
    </div>
    <div class="form">
      <button class="btn btn-success" type="submit">Remove user</button>
      <br><br>
    </div>
  </form>

  <div class="title">
    <h3>Delete record</h3>
  </div>

  <form class="form" role="form" method="post" action="{{ url_for('user.delete_record') }}">
    {{ remove_record.csrf_token }}
    {{ remove_record.hidden_tag() }}
    {{ wtf.form_errors(remove_record, hiddens="only") }}

    <div class="form-row">
      {{ wtf.form_field(remove_record.strat_no )}}
      
    </div>
    <div class="form">
      <button class="btn btn-warning" type="submit">Remove strat record</button>
      <br><br>
    </div>
  </form>
{% endblock %}

project/client/templates/user/data_entry.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<div class="content-header">
  <div>
    <h1>Stratigraphic data entry form</h1>
    <hr>
    <p>
      <h3>Welcome, <em>{{ current_user.username }}</em></h3>
    </p>
  </div>
</div>  


<form class="form" role="form" method="post" action="{{ url_for('user.new_entry') }}">
  {{ entry_form.csrf_token }}
  {{ entry_form.hidden_tag() }}
  {{ wtf.form_errors(entry_form, hiddens="only") }}

  <div class="form">
    {{ wtf.form_field(entry_form.unit_name )}}
    {{ wtf.form_field(entry_form.ASUD_No) }}
    {{ wtf.form_field(entry_form.ASUD_definition_card) }}
    {{ wtf.form_field(entry_form.strat_no) }}
    {{ wtf.form_field(entry_form.map_symbol )}}
    {{ wtf.form_field(entry_form.province) }}
    {{ wtf.form_field(entry_form.domain) }}
    {{ wtf.form_field(entry_form.unit_description) }}
    {{ wtf.form_field(entry_form.unit_summary )}}
    {{ wtf.form_field(entry_form.type_locality) }}
    {{ wtf.form_field(entry_form.unit_definition) }}
    {{ wtf.form_field(entry_form.unit_correlation) }}
    {{ wtf.form_field(entry_form.unit_distribution )}}
    {{ wtf.form_field(entry_form.unit_thickness) }}
    {{ wtf.form_field(entry_form.unit_lithology) }}
    {{ wtf.form_field(entry_form.unit_deposition_env) }}
    {{ wtf.form_field(entry_form.unit_contact_relations )}}
    {{ wtf.form_field(entry_form.unit_geochronology) }}
    {{ wtf.form_field(entry_form.unit_geochemistry) }}
    {{ wtf.form_field(entry_form.unit_geophysical_expression) }}
    {{ wtf.form_field(entry_form.references )}}
  </div>
  <div class="form">
    <button class="btn btn-success" type="submit">Add new record</button>
    <br><br>
  </div>
</form>

{% endblock %}

project/client/templates/user/edit_record.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<div class="content-header">
  <div class="row">
    <div class="col-9">
      <h1>Stratigraphic data edit form</h1>
    </div>
    <div class="col-3">
      <div class="form">
        <a href="{{ url_for('user.index') }}" class="btn btn-warning" >Cancel</a>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="text">
  <p>
    <h3>Welcome, <em>{{ current_user.username }}</em></h3>
  </p>
</div>  

<form class="form" role="form" method="post" >
  {{ entry_form.csrf_token }}
  

  <div class="form">
    {{ wtf.form_field(entry_form.unit_name)}}
    {{ wtf.form_field(entry_form.ASUD_No) }}
    {{ wtf.form_field(entry_form.ASUD_definition_card) }}
    {{ wtf.form_field(entry_form.strat_no) }}
    {{ wtf.form_field(entry_form.map_symbol)}}
    {{ wtf.form_field(entry_form.province) }}
    {{ wtf.form_field(entry_form.domain) }}
    {{ wtf.form_field(entry_form.unit_description) }}
    {{ wtf.form_field(entry_form.unit_summary )}}
    {{ wtf.form_field(entry_form.type_locality) }}
    {{ wtf.form_field(entry_form.unit_definition) }}
    {{ wtf.form_field(entry_form.unit_correlation) }}
    {{ wtf.form_field(entry_form.unit_distribution )}}
    {{ wtf.form_field(entry_form.unit_thickness) }}
    {{ wtf.form_field(entry_form.unit_lithology) }}
    {{ wtf.form_field(entry_form.unit_deposition_env) }}
    {{ wtf.form_field(entry_form.unit_contact_relations )}}
    {{ wtf.form_field(entry_form.unit_geochronology) }}
    {{ wtf.form_field(entry_form.unit_geochemistry) }}
    {{ wtf.form_field(entry_form.unit_geophysical_expression) }}
    {{ wtf.form_field(entry_form.references )}}
  </div>
  <div class="form">
    <button class="btn btn-success" type="submit">Update record</button>
    <br><br>
  </div>
</form>

{% endblock %}

project/client/templates/user/index.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<div class="content-header">
  <div>
    <h1>SA Stratigraphic units compiled</h1>
    <hr>
  </div>
</div>

<div class="main">
  <h4>Total number of records: {{ entry_count}} </h4> 
</div>
<div class="table">
  {{ table }}
</div>


{% endblock %}

project/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Login</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.username) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      
    </div>
  </form>

{% endblock %}

project/client/templates/user/reset_password.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Reset Your Password</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.password2) }}

      <button class="btn btn-success" type="submit">Request password reset</button>
      <br><br>
      
    </div>
  </form>

{% endblock %}

project/client/templates/user/reset_password_request.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Reset Password Request</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.email) }}

      <button class="btn btn-success" type="submit">Request password reset</button>
      <br><br>
      
    </div>
  </form>

{% endblock %}

project/client/templates/user/view_record.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<div class="content-header">
  <div class="row">
    <div class="col-9">
      <h1>Stratigraphic unit record</h1>
    </div>
    <div class="col-3">
      <div class="form">
        <a href="{{ url_for('user.index') }}" class="btn btn-success" >Close record</a>
      </div>
    </div>
  </div>
</div>  

<hr>

<div class="body">
  <div>
    {% for key, value in record.items() %}
    <h4>{{key}}</h4>
    <div class="container pt-2 border", style="white-space: pre-line; word-wrap: break-word;"><p>{{value}}</p></div>
    {% endfor %}
  </div>
</div>

{% endblock %}